Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
segments = {s.get("segment_id"): {**s, "flight_id": flight["flight_id"]}
             for campaign in meta.values()
             for platform in campaign.values()
             for flight in platform.values()
             for s in flight["segments"]
            }
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_2970471/126495523.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m segments = {s.get("segment_id"): {**s, "flight_id": flight["flight_id"]}
[0m[1;32m      2[0m              [0;32mfor[0m [0mcampaign[0m [0;32min[0m [0mmeta[0m[0;34m.[0m[0mvalues[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m              [0;32mfor[0m [0mplatform[0m [0;32min[0m [0mcampaign[0m[0;34m.[0m[0mvalues[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m              [0;32mfor[0m [0mflight[0m [0;32min[0m [0mplatform[0m[0;34m.[0m[0mvalues[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m              [0;32mfor[0m [0ms[0m [0;32min[0m [0mflight[0m[0;34m[[0m[0;34m"segments"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m/tmp/ipykernel_2970471/126495523.py[0m in [0;36m<dictcomp>[0;34m(.0)[0m
[1;32m      3[0m              [0;32mfor[0m [0mplatform[0m [0;32min[0m [0mcampaign[0m[0;34m.[0m[0mvalues[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m              [0;32mfor[0m [0mflight[0m [0;32min[0m [0mplatform[0m[0;34m.[0m[0mvalues[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m              [0;32mfor[0m [0ms[0m [0;32min[0m [0mflight[0m[0;34m[[0m[0;34m"segments"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m             }

[0;31mTypeError[0m: 'NoneType' object is not iterable
TypeError: 'NoneType' object is not iterable

