Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True)

# 1st: plot flight altitude and radar reflectivity
ax1.plot(ds_mirac_a_sel.time, ds_mirac_a_sel.altitude*1e-3, label='Flight altitude', color='k')

im = ax1.pcolormesh(ds_mirac_a_sel.time, ds_mirac_a_sel.height*1e-3, 10*log10(ds_mirac_a_sel.Ze).T, vmin=-40, vmax=30, cmap='jet', shading='nearest')
fig.colorbar(im, ax=ax1, label='Radar reflectivity [dBz]')
ax1.set_ylim(-0.25, 3.5)
ax1.set_ylabel('Height [km]')
ax1.legend(frameon=False, loc='upper left')

# 2nd: plot 89 GHz TB
ax2.plot(ds_mirac_a_sel.time, ds_mirac_a_sel.TB_89, label='Tb(89 GHz)', color='k')
ax2.set_ylim(177, 195)
ax2.set_ylabel('$T_b$ [K]')
ax2.set_xlabel('Time (hh:mm) [UTC]')
ax2.legend(frameon=False, loc='upper left')

ax2.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))

plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_3109164/717495929.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0;31m# 1st: plot flight altitude and radar reflectivity[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0max1[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mds_mirac_a_sel[0m[0;34m.[0m[0mtime[0m[0;34m,[0m [0mds_mirac_a_sel[0m[0;34m.[0m[0maltitude[0m[0;34m*[0m[0;36m1e-3[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34m'Flight altitude'[0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m'k'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0mim[0m [0;34m=[0m [0max1[0m[0;34m.[0m[0mpcolormesh[0m[0;34m([0m[0mds_mirac_a_sel[0m[0;34m.[0m[0mtime[0m[0;34m,[0m [0mds_mirac_a_sel[0m[0;34m.[0m[0mheight[0m[0;34m*[0m[0;36m1e-3[0m[0;34m,[0m [0;36m10[0m[0;34m*[0m[0mlog10[0m[0;34m([0m[0mds_mirac_a_sel[0m[0;34m.[0m[0mZe[0m[0;34m)[0m[0;34m.[0m[0mT[0m[0;34m,[0m [0mvmin[0m[0;34m=[0m[0;34m-[0m[0;36m40[0m[0;34m,[0m [0mvmax[0m[0;34m=[0m[0;36m30[0m[0;34m,[0m [0mcmap[0m[0;34m=[0m[0;34m'jet'[0m[0;34m,[0m [0mshading[0m[0;34m=[0m[0;34m'nearest'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.8/dist-packages/xarray/core/common.py[0m in [0;36m__getattr__[0;34m(self, name)[0m
[1;32m    237[0m                 [0;32mwith[0m [0msuppress[0m[0;34m([0m[0mKeyError[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    238[0m                     [0;32mreturn[0m [0msource[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 239[0;31m         raise AttributeError(
[0m[1;32m    240[0m             [0;34m"{!r} object has no attribute {!r}"[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mtype[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m.[0m[0m__name__[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    241[0m         )

[0;31mAttributeError[0m: 'Dataset' object has no attribute 'altitude'
AttributeError: 'Dataset' object has no attribute 'altitude'

